#!/bin/bash
# $IMAGE_NAME var is injected into the build so the tag is correct. 
docker build --no-cache --rm \
  --build-arg VCS_REF=`git rev-parse --short HEAD` \
  --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` \
  --build-arg VERSION=`cat VERSION` \
  -f "Dockerfile" \
  -t $IMAGE_NAME .
